# Generated by Django 4.2.17 on 2024-12-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('FIAT', 'Fiat'), ('TOYOTA', 'Toyota'), ('FORD', 'Ford'), ('CHEVROLET', 'Chevrolet')], default='Ford', max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('serie_carroceria', models.CharField(max_length=50)),
                ('serie_motor', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('PARTICULAR', 'Particular'), ('TRANSPORTE', 'Transporte'), ('CARGA', 'Carga')], default='Particular', max_length=20)),
                ('precio', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
