# Generated by Django 4.2.17 on 2024-12-18 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='serie_carroceria',
            new_name='serial_carroceria',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='serie_motor',
            new_name='serial_motor',
        ),
    ]
