# Generated by Django 4.2.17 on 2024-12-18 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_rename_serie_carroceria_vehiculo_serial_carroceria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'Tienes permiso para visualizar el catalogo de vehiculos'), ('addVehiculo', 'Puedes agregar un vehiculo al catalogo')]},
        ),
    ]
