# Generated by Django 4.2.17 on 2024-12-18 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'Tienes permiso para visualizar el catalogo de vehiculos'), ('puede_agregar_vehiculo', 'Puedes agregar un vehiculo al catalogo')]},
        ),
    ]
